version: "3.9"
services:
  nvim:
    build: ./DevelopmentEnvironment/
    container_name: "nvim"
    labels:
      description: "dev env. with neovim and local folder" 
      authors: "Jonathan Zollinger"
    tty: true
    stdin_open: true
  pwsh:
    build: ./powershell/
    container_name: "pwsh"
    labels:
      description: "powershell 7 with powercli and vmware scripts"
      authors: "Jonathan Zollinger"
    tty: true
    stdin_open: true
    volumes: 
      - type: bind
        source: ./powershell
        target: /my_powershell_modules
  rhel:
    image: "redhat-8.4"
    container_name: "rhel"
    build:
      context: ./RHEL/
      args: 
        PKG_DEPS: "unzip git wget curl dirmngr gnupg2 binutils net-tools glow skate gum man ca-certificates vim-enhanced policycoreutils-python-utils.noarch"
    tty: true
    stdin_open: true
  tomcat:
    build:
      context: ./tomcat/
      args:        
        TOMCAT_TARBALL_URI: "https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.90/bin/apache-tomcat-7.0.90.tar.gz"
        ZULU_JDK_TARBALL_URI: "https://cdn.azul.com/zulu/bin/zulu8.68.0.21-ca-jdk8.0.362-linux_x64.tar.gz"
    image: "tomcat7.9-ubi8.4"
    container_name: "tomcat"
    labels:
      description: "tomcat 7.9 on ubi8.4 configured similar to Mico Focus' standard configuration"
      authors: "Jonathan Zollinger"
    tty: true
    stdin_open: true
  tube:
    image: prologic/tube
    ports:
      - 8000:8000